spring:
  mvc:
    problemdatails:
      enable: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: chhean
    password: spring
  h2:
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
